export default {
    HeroHeading: 'AI Logo Maker',
    HeroSubheading: 'Perfect Logos for Apps, Businesses, and Websites',
    HeroDesc: 'Craft unique and professional logos effortlessly with our AI Logo Generator.',
    InputTitlePlaceholder: 'Enter your logo name',
    LogoTitle: 'Logo Title',
    LogoTitleDesc: 'Add your Business, App, or Website Name for a Custom Logo',
    LogoDescTitle: 'Describe Your Logo Vision',
    LogoDescDesc: 'Share your ideas, themes, or  inspirations to create a custom logo',
    LogoIdeaTitle: 'Select Your Design Idea',
    LogoIdeaDesc: 'Choose a design style that aligns with your vision, or brand',
    LogoDesignTitle: 'Choose Your Logo Style',
    LogoDesignDesc: 'Select the type of logo design that best represents your brand',
    LogoColorPaletteTitle: 'Choose Your Color Palette',
    LogoColorPaletteDesc: 'Pick the colors that reflect your brands personality',
}